Add Atom Pair docs and fixes
scikit-fingerprints/scikit-fingerprints pull request #117
Opened 2024-04-01 12:31 UTC by j-adamczyk

2024-04-01 19:48 UTC, mjste commented on docs/make.bat
maybe we should leave CRLF, as .bat files are meant for windows

2024-04-01 20:33 UTC, mjste commented on docs/_templates/class.rst
move it to _templates/autosummary/class.rst
Without it, the file does not affect anything

2024-04-01 20:35 UTC, mjste commented on docs/_templates/class.rst
> +      ~{{ name }}.{{ item }}
please add 
`
{% if item != '__init__' %} 
  ~{{ name }}.{{ item }}
{% endif %}
`

2024-04-01 20:54 UTC, mjste requested changes
at least class.rst must be moved

2024-04-02 08:02 UTC, j-adamczyk commented on docs/make.bat
done

2024-04-02 08:14 UTC, j-adamczyk commented on docs/_templates/class.rst
> +      ~{{ name }}.{{ item }}
done

2024-04-02 09:25 UTC, mjste approved these changes

2024-04-02 11:52 UTC, merged