Add Klekota-Roth fingerprint
scikit-fingerprints/scikit-fingerprints pull request #148
Opened 2024-04-23 09:01 UTC by BlazejNowicki

### Klekota-Roth fingerprint
[ref 1](https://cdk.github.io/cdk/latest/docs/api/org/openscience/cdk/fingerprint/KlekotaRothFingerprinter.html), [ref 2](https://github.com/cdk/cdk/blob/267f3b67efe554d1ffbfb308514ef04141e9f0be/descriptor/fingerprint/src/main/java/org/openscience/cdk/fingerprint/KlekotaRothFingerprinter.java)

Tasks:
- [x] Add Substructure Fingerprint
- [x] Test Substructure Fingerprint
- [x] Add Klekota-Roth Fingerprint
- [ ] Test Klekota-Roth Fingerprint
- [ ] Add docs

2024-04-24 09:11 UTC, j-adamczyk requested changes

2024-04-25 16:34 UTC, BlazejNowicki commented on tests/fingerprints/klekota_roth.py
> +#         KlekotaRothFingerprint(invalid_substructures)
Removed. This tests should be only for `SubstrucureFingerprint`

2024-04-25 18:29 UTC, BlazejNowicki commented on skfp/fingerprints/substructure_fp.py
> +            ]
Now that I added type conversion to uint32 and uint8 respectively I think having these separately is more readable.

2024-04-26 13:03 UTC, j-adamczyk requested changes

2024-04-26 17:42 UTC, mjste approved these changes

2024-04-26 18:30 UTC, j-adamczyk approved these changes

2024-04-26 18:30 UTC, merged