Add ECFP docs
scikit-fingerprints/scikit-fingerprints pull request #179
Opened 2024-06-13 14:09 UTC by j-adamczyk

2024-06-13 14:13 UTC, mjste approved these changes

2024-06-13 14:53 UTC, my-alaska requested changes

2024-06-13 14:53 UTC, my-alaska commented on skfp/fingerprints/ecfp.py
> +    Each subgraph get an identifier based on atom types in their radius, which is
Use "All subrgaphs" or change the rest of the sentence to singular form.

2024-06-13 14:53 UTC, my-alaska commented on skfp/fingerprints/ecfp.py
> +    thenhashed. Atom types (invariants) by default are based on Daylight invariants:
"then hashed"

2024-06-13 14:53 UTC, my-alaska commented on skfp/fingerprints/ecfp.py
> +        Whether to check if atom is part of a when computing atom types.
It looks like a ring part is missing in "is part of a [...] when"

2024-06-15 15:17 UTC, my-alaska approved these changes

2024-06-15 15:25 UTC, merged