Added Weiner index fingerprint
scikit-fingerprints/scikit-fingerprints pull request #330
Opened 2024-11-25 21:39 UTC by chmurzak

2024-11-26 07:50 UTC, j-adamczyk requested changes

2024-11-26 07:50 UTC, j-adamczyk commented on skfp/fingerprints/weiner_index.py
> +
This shouldn't be a fingerprint, this is a single descriptor. It is, however, a part of other descriptors, and a useful thing to have.

Create `descriptors` directory next to `fingerprints`, and maybe `topological.py` file there, and put Wiener index in there. Also, it should be a function `wiener_index(mol, distance_matrix: Optional[np.ndarray] = None) -> int`. If user has a precomputed distance matrix, it should be reused.

2024-11-26 07:50 UTC, j-adamczyk commented on skfp/fingerprints/weiner_index.py
> +
Also, add the appropriate citation. See other fingerprints for a format.

2024-11-26 07:50 UTC, j-adamczyk commented on skfp/fingerprints/weiner_index.py
> +                weiner_indices.append(0.0)
This should throw an error

2024-11-26 07:50 UTC, j-adamczyk commented on skfp/fingerprints/weiner_index.py
> +            weiner_index = np.sum(distance_matrix) / 2
This can be `// 2`, since sum of distances will always be an integer

2024-11-26 07:50 UTC, j-adamczyk commented on tests/fingerprints/weiner_index.py
> +
This requires more tests with known values, at least:
1. Examples from the original Wiener's paper
2. Single atom molecule
3. Linear molecule, e.g. butane
4. Ring-like molecule, e.g. benzene

2025-01-05 10:27 UTC, iedylag commented
Changes after review:
 1. Created descriptors directory and topological.py file 
 2. Added few descriptors as functions (reusing precomputed distance matrix)
 3. Added tests with knows values

2025-01-05 19:20 UTC, mjste commented
* I think descriptors should be rather a part of the library, so directory descriptors should become skfp/descriptors
* Some docstring for Topologcal Descriptors missing
* Sync with master

2025-01-05 19:22 UTC, mjste requested changes

2025-01-05 19:22 UTC, mjste commented on .pre-commit-config.yaml
Leave line endings as they were

2025-01-05 19:22 UTC, mjste commented on descriptors/topological.py
Move it to skfp/descriptors. Otherwise they will be not available in library

2025-01-05 22:00 UTC, j-adamczyk requested changes
I also second all comments by @mjste, and added my own

2025-01-05 22:00 UTC, j-adamczyk commented on tests/descriptors/topological.py
> +    assert result == pytest.approx(expected_value, abs=1e-6)
Also, add tests that check both provided and not provided `distance_matrix`

2025-01-06 15:30 UTC, iedylag commented
Changes after review:

- Moved descriptors to skfp
- Refactored descriptors to functions
- Added appropriate docstrings with citation
- Added separate tests

2025-01-06 21:33 UTC, j-adamczyk requested changes
Also add docs in `docs` directory, with appropriate `.rst` files

2025-01-06 21:33 UTC, j-adamczyk commented on skfp/descriptors/__init__.py
This file should import descriptors from their module

2025-01-06 21:33 UTC, j-adamczyk commented on .pre-commit-config.yaml
> -repos:
Why change line endings? Revert this

2025-01-06 21:33 UTC, j-adamczyk commented on skfp/descriptors/topological.py
> +    .. [1] Chen, Ailian, Xianzhu Xiong, and Fenggen Lin.
1. Why this reference? The original one is https://pubs.acs.org/doi/abs/10.1021/ja01193a005, second one could be e.g. https://www.sciencedirect.com/science/article/abs/pii/B9781898563761500068.
2. Missing backticks and underscore at the end, see e.g. https://github.com/scikit-fingerprints/scikit-fingerprints/blob/master/skfp/fingerprints/atom_pair.py#L119. This will create a hyperlink in the docs

2025-01-06 21:33 UTC, j-adamczyk commented on skfp/descriptors/topological.py
> +        The molecular graph for which the Wiener index is to be calculated.
Just `The molecule`, since it's quite more than just a graph

2025-01-06 21:33 UTC, j-adamczyk commented on skfp/descriptors/topological.py
> +    >>> from rdkit import Chem
Import `MolFromSmiles` directly

2025-01-06 21:33 UTC, j-adamczyk commented on skfp/descriptors/topological.py
> +    It is derived by dividing the Wiener index by the total number of atom pairs in the molecule.
Maybe also note that this makes it independent of the molecule size.

2025-01-06 21:33 UTC, j-adamczyk commented on skfp/descriptors/topological.py
> +        The molecular graph for which the Wiener index is to be calculated.
It applies to all descriptions

2025-01-06 21:33 UTC, j-adamczyk commented on skfp/descriptors/topological.py
> +    .. [1] Chen, Ailian, Xianzhu Xiong, and Fenggen Lin.
Second point applies to all docstrings

2025-01-06 21:33 UTC, j-adamczyk commented on skfp/descriptors/topological.py
> +    >>> from rdkit import Chem
Applies to all docstrings

2025-01-06 21:33 UTC, j-adamczyk commented on skfp/descriptors/topological.py
> +"""
Missing tab

2025-01-06 21:33 UTC, j-adamczyk commented on skfp/descriptors/topological.py
> +        <https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/pychem/manual.pdf>
Proper reference is `Rouvray, D. H. In Chemical Applications of Topology and Graph Theory; King, R. B., Ed.; Elsevier: Amsterdam, 1983; pp 159-177.`, or https://pubs.acs.org/doi/10.1021/ci9502461

2025-01-06 21:33 UTC, j-adamczyk commented on skfp/descriptors/topological.py
> +"""
Missing tab

2025-01-06 21:33 UTC, j-adamczyk commented on skfp/descriptors/topological.py
> +        Croatica chemica acta 86.4 (2013): 352.
Should be capitalized, i.e. Croatica Chemica Acta

2025-01-06 21:33 UTC, j-adamczyk commented on skfp/descriptors/topological.py
> +    return sum(degree_sequence ** 2)
It's cheaper to do:
```
sum(atom.GetDegree() ** 2 for atom in mol.GetAtoms())
```

2025-01-06 21:33 UTC, j-adamczyk commented on skfp/descriptors/topological.py
> +        <https://onlinelibrary.wiley.com/doi/abs/10.1002/qua.26627>
This is a good second reference, but use original Wiener index paper as first reference

2025-01-06 21:33 UTC, j-adamczyk commented on skfp/descriptors/topological.py
> +            i for i, atom in enumerate(mol.GetAtoms()) if atom.GetAtomicNum() == 6  # Carbon atomic number is 6
You can also do `.GetSymbol() == "C"`

2025-01-06 21:33 UTC, j-adamczyk commented on tests/descriptors/topological.py
> +        ("pyrimidine", 1.9642857142857142),
Round this to e.g. 3rd decimal place and then compare, it's more readable and still accurate enough

2025-01-06 21:33 UTC, j-adamczyk commented on tests/descriptors/topological.py
> +    mol = mol_tuple[1]
Just change `diverse_molecules` to return `dict[str, Mol]` and then you can simply select by name

2025-01-06 21:33 UTC, j-adamczyk commented on tests/descriptors/topological.py
> +    mol = mol_tuple[1]
In fact, this should simply all tests here

2025-01-06 21:33 UTC, j-adamczyk commented on tests/descriptors/topological.py
> +    ]
You can also calculate the distance matrices here, and use them in tests: first without passing it (descriptor function computing it internally), then passing. Both results should be the same.

2025-01-06 21:33 UTC, j-adamczyk commented on skfp/descriptors/topological.py
> +def graph_distance_index(mol: Mol, distance_matrix: Optional[np.ndarray] = None) -> float:
This returns `int`

2025-01-06 21:33 UTC, j-adamczyk commented on skfp/descriptors/topological.py
> +def graph_distance_index(mol: Mol, distance_matrix: Optional[np.ndarray] = None) -> float:
Or at least it should, cast if necessary

2025-01-06 21:33 UTC, j-adamczyk commented on skfp/descriptors/topological.py
> +    carbon_only : bool, default=False
Edge case - what if molecules does not have any carbons? This should raise an explicit error then. You can check this, i.e. if `atom_indices` is empty or not. Also, write a test for this.

2025-01-06 21:33 UTC, j-adamczyk commented on tests/descriptors/topological.py
> +    assert (result == pytest.approx(expected_value, abs=1e-6))
Why additional parentheses?

2025-01-06 21:33 UTC, j-adamczyk commented on tests/descriptors/topological.py
> +    assert result == pytest.approx(expected_value, abs=1e-6)
You are comparing integers here, no need for approximate testing, since it's much slower

2025-01-10 12:58 UTC, iedylag commented on .pre-commit-config.yaml
> -repos:
I changed this in previous commit. Couldn't revert because of the merge with master, so i copied the content of this file from the master branch. This is the current version of the file.

2025-01-10 14:00 UTC, iedylag commented on skfp/descriptors/topological.py
> +        <https://onlinelibrary.wiley.com/doi/abs/10.1002/qua.26627>
Are any of these suitable for first reference?
1. https://pubs.acs.org/doi/10.1021/ci970122j
2. https://match.pmf.kg.ac.rs/electronic_versions/Match66/n1/match66n1_293-304.pdf

2025-01-10 14:23 UTC, iedylag commented on tests/descriptors/topological.py
> +    assert result == pytest.approx(expected_value, abs=1e-6)
I didn't know it would slow down the tests. I removed it from every test because it wasn't necessary in any test case.

2025-01-12 14:59 UTC, j-adamczyk approved these changes
I made a few smaller changes myself. Also note the changes in the documentation.

2025-01-12 15:15 UTC, j-adamczyk approved these changes

2025-01-12 17:02 UTC, j-adamczyk approved these changes

2025-01-12 17:13 UTC, mjste approved these changes

2025-01-12 17:38 UTC, merged